- name: Install and start tuned service
  hosts: all
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Please enter your sudo password"
      private: true
  tasks:
    - name: Ensure tuned package is installed
      yum:
        name: tuned
        state: present

    - name: Start and enable tuned service
      service:
        name: tuned
        enabled: true
        state: started
